basic_thread:
	g++ basic_thread.cpp -o $@

thread_parameters:
	g++ thread_parameters.cpp -o $@

mutex_demo:
	g++ mutex_demo.cpp -pthread -o $@

mutex_RAII:
	g++ mutex_with_RAII.cpp -pthread -o $@

condition_variable:
	g++ condition_variable.cpp -pthread -o $@

prom_fut:
	g++ promise_future.cpp -pthread -o $@

prod_cons_queue:
	g++ producer_consumer_queue.cpp -pthread -o $@

prod_cons_queue_V2:
	g++ producer_consumer_queue_V2.cpp -pthread -o $@

async_demo:
	g++ async_demo.cpp -pthread -o $@

thread_class:
	g++ thread_class.cpp -pthread -o $@

random_wait_async:
	g++ random_wait_async.cpp -pthread -o $@

clean:
	rm basic_thread thread_parameters mutex_demo mutex_RAII condition_variable prom_fut prod_cons_queue thread_class